### ISSUE TITLE
[Bug] Plugin causes console noise when used alongside debug.js

### ISSUE THREAD

**Issue by AdrianBannister** [sysgears/webpack-virtual-modules#107]
- [x] I'd be willing to submit the fix

**Describe the bug**

When using the `DEBUG` environment variable to control what log messages we would like to see while using the [debug](https://www.npmjs.com/package/debug) package we are getting flooded by `console.log` messages from this plugin.

**To Reproduce**

Run a webpack build with this plugin loaded and set the `DEBUG` environment variable to anything. It will spit out tons of `console.log` messages.

**Additional context**

The offending code is here: https://github.com/sysgears/webpack-virtual-modules/blob/752ee23bf9aefd8590c6bf6e2ddfa0fb212bb04b/src/index.ts#L137-L139

Might I suggest to changing the environment variable being checked to something like `WVM_DEBUG`. I'd happily create a PR if you are okay with this.

**Comment by larixer** [comment]
@AdrianBannister Yep, such a PR sounds good

**Comment by larixer** [comment]
Closed with #108
