### ISSUE TITLE
Ability to reset files

### ISSUE THREAD

**Issue by fringd** [sysgears/webpack-virtual-modules#13]
I'm using this to overlay my files on a filesystem. I'd like to be able to "reset" a file to its original contents. I can do this with writeModule and readFileSync right now, but it would be nice if writeModules('filename', contents) had a resetModule('filename') to undo the machinations for subsequent runs.

**Comment by vlasenko** [comment]
@fringd I would rather name it `deleteVirtualModule(filePath)`, or `unlinkModule(filePath)`. Would you be willing to submit Pull Request for this feature. Preferably with adding tests, but I will accept it without tests too if the code will be reliable.

**Comment by fringd** [comment]
That sounds good to me. Do you know if there's a way to do this without just reading the file and re-writing it like i said? is there a way to just remove it from the virtual file system or cache or whatever?

**Comment by vlasenko** [comment]
@fringd Yes, I am certain that there is a way, but to make good implementation - you will have to delve into internals of webpack and its companion packages.

**Comment by fringd** [comment]
I notice in your implementation you're overriding a method called "purge" do you think this does what I want?

**Comment by fringd** [comment]
so compiler.inputFileSystem.purge(fileName) does exactly what I want it seems. maybe we don't need this feature.

**Comment by vlasenko** [comment]
@fringd Yes, if it is working, then we are done :)
