### ISSUE TITLE
Does not work with WatchIgnorePlugin 

### ISSUE THREAD

**Issue by ChrisSG** [sysgears/webpack-virtual-modules#15]
Line 50 of webpack-virtual-modules/index.js breaks when applying WatchIgnorePlugin as the attribute "watcher" is not present on the IngoringWatchFileSystem

if (self._watcher && self._watcher.watchFileSystem.watcher.fileWatchers.length) {

WatchIgnorePlugin rejected a PR. See https://github.com/webpack/webpack/pull/9097

**Comment by vlasenko** [comment]
Closing this issue as `wontfix`, I don't have idea how it can be fixed in `webpack-virtual-modules`, IMO it can be fixed only inside `webpack`. If you have idea how to fix it in `webpack-virtual-modules`, please reopen this issue.

**Comment by vlasenko** [comment]
@ChrisSG It has been implemented in #32
