### ISSUE TITLE
Incorrectly used fileWatcher, that causing writeModule not trigger recompile with webpack-dev-server

### ISSUE THREAD

**Issue by miserylee** [sysgears/webpack-virtual-modules#155]
The incorrect code is below:
https://github.com/sysgears/webpack-virtual-modules/blob/c45595835906a201f9441a2f3c9d688f5689767c/src/index.ts#L165

In where I print the `fileWatcher` variable, it likes below:
![image](https://user-images.githubusercontent.com/16648966/175295209-44ec41c2-4076-43ca-9bef-354e47b11e9e.png)

The object structure is defined here in `watchpack`:
https://github.com/webpack/watchpack/blob/dc690bbaea140820f1d9c7c2ec4dff8902798ff9/lib/watchpack.js#L70

The properties `.path` and `.directoryWatcher` is not directly appear in the `fileWatcher` variable, but `fileWatcher.watcher`.

When I changed the code to this, it works as expected:
![image](https://user-images.githubusercontent.com/16648966/175296430-65d65d6e-5f68-46cf-8028-8c16a9c13bfd.png)

**Comment by larixer** [comment]
Published as webpack-virtual-modules@0.4.4, fixed by #156
