### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by xshua06** [sysgears/webpack-virtual-modules#162]
- [ ] I'd be willing to submit the fix

**Describe the bug**

Generating dynamic virtual modules not update when writeModule.

**To Reproduce**
![image](https://user-images.githubusercontent.com/1212421/204429579-7f2117ce-2cac-48b5-a910-3333cd2e6d7d.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/1212421/204429409-98d24e5e-976d-4143-b783-a16120c2fe72.png)

**Environment if relevant (please complete the following information):**

├─ webpack-dev-server@4.11.1
├─ webpack-merge@5.8.0
├─ webpack-virtual-modules@0.4.6
├─ webpack@5.75.0

 - OS: [e.g. OSX, Linux, Windows, ...]  Mac OSX
 - Node version [e.g. 8.15.0, 10.15.1, ...] v16.15.0
 - Webpack version [e.g. 4.26.1, ...] 5.75.0

**Additional context**

**Comment by larixer** [comment]
Please reopen with full reproduction steps. For now I'm closing the issue as invalid.
