### ISSUE TITLE
[Question] - Is it possible generate new virtual modules based on file-system changes?

### ISSUE THREAD

**Issue by rnarcos** [sysgears/webpack-virtual-modules#163]
Hi.

I'm trying to create (for the first time) a webpack plugin that (in a few words) creates a virtual module**s** based on the application files. I am able to correctly write a virtual module thanks to the examples explained in this repo, but I'm wondering if it would be possible to re-generate the virtual modules contents based on the changes on the "physical" files.

[]s,

**Comment by larixer** [comment]
Hi,

Yes, the examples in this repo re-generate virtual modules contents.
