### ISSUE TITLE
[Bug] ModuleNotFoundError happened ,when I compile two project in the same progress 

### ISSUE THREAD

**Issue by cai-zhuo** [sysgears/webpack-virtual-modules#165]
- [ ] I'd be willing to submit the fix
Sorry, it's too hard to submit the fix.

**Describe the bug**

Hello, sorry to report this issue, but I really can't solve this problem, thanks to help!

ModuleNotFoundError happened, when I compile two project in the same progress.

**To Reproduce**
Just use simple code to reproduce.
// index.js

```
const foo = require("module-foo");
console.log(foo);
```

// webpack.config.js
```
var VirtualModulesPlugin = require("webpack-virtual-modules");

var virtualModules = new VirtualModulesPlugin({
  "node_modules/module-foo.js": 'module.exports = { foo: "foo" };',
});

/**
 * @type {()=>import('webpack').Configuration}
 */
const config = () => ({
  entry: "./index.js",
  output: {
    path: require("path").resolve(__dirname, "./dist"),
  },

  plugins: [virtualModules],
});

/**
 * @type {()=>import('webpack').Configuration}
 */
const another = () => ({
  entry: "./index.js",
  output: {
    path: require("path").resolve(__dirname, "./dist2"),
  },
  plugins: [virtualModules],
});

module.exports = [another, config];
```

**Environment if relevant (please complete the following information):**

System:
    OS: macOS 11.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.31 GB / 32.00 GB
  Binaries:
    Node: 17.9.1 - ~/Library/Caches/fnm_multishells/12569_1672806001367/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/57324_1672722484275/bin/yarn
    npm: 8.11.0 - ~/Library/Caches/fnm_multishells/12569_1672806001367/bin/npm
  Packages:
    webpack: ^5.75.0 => 5.75.0 
    webpack-cli: ^5.0.1 => 5.0.1 
    webpack-virtual-modules: ^0.5.0 => 0.5.0

**Comment by larixer** [comment]
@cai-zhuo You are using the same instance of `webpack-virtual-modules` for two webpack instances, this is not supported, you must use one instance per webpack process, i.e.:
```javascript
var VirtualModulesPlugin = require("webpack-virtual-modules");

var virtualModules1 = new VirtualModulesPlugin({
  "node_modules/module-foo.js": 'module.exports = { foo: "foo" };',
});

var virtualModules2 = new VirtualModulesPlugin({
  "node_modules/module-foo.js": 'module.exports = { foo: "foo" };',
});

/**
 * @type {()=>import('webpack').Configuration}
 */
const config = () => ({
  entry: "./index.js",
  output: {
    path: require("path").resolve(__dirname, "./dist"),
  },

  plugins: [virtualModules1],
});

/**
 * @type {()=>import('webpack').Configuration}
 */
const another = () => ({
  entry: "./index.js",
  output: {
    path: require("path").resolve(__dirname, "./dist2"),
  },
  plugins: [virtualModules2],
});

module.exports = [another, config];
```

**Comment by cai-zhuo** [comment]
Get!   : )

**Comment by cai-zhuo** [comment]
Single instance cannot be used in two webpack instances. Is it because "virtualStats" ?  @larixer
