### ISSUE TITLE
What are some real usecases of this plugin?

### ISSUE THREAD

**Issue by nyngwang** [sysgears/webpack-virtual-modules#174]
As title. I use webpack for frontend development, specifically, React. Is this plugin can do things like HMR and replace some of those existing plugins? If not, what are the real usecases this plugin will be helpful? I'm a learner and I want to know it. Thank you.

**Comment by larixer** [comment]
You can lookup dependants of this plugin at npm registry:
https://www.npmjs.com/package/webpack-virtual-modules?activeTab=dependents
