### ISSUE TITLE
Problem with virtual files in the main public folder

### ISSUE THREAD

**Issue by cblanquera** [sysgears/webpack-virtual-modules#29]
Thanks for writing this package. Your a real time saver :) . I tried everything you documented and all works great! I even tried making a virtual entry point and that works too. I'm only really having one problem, so I hope you can help me with this or clarify.

### Expected

Trying to add a Virtual Module located (virtually) in the public directory. Other JS files should be able to access this file relatively. For example in the entry file, the `/asset/number-one.js` can be required like the following.

```js
require('./asset/number-one')
```

and another random file `/something/random.js` could require `/asset/number-one.js` like the following.

```js
require('../asset/number-one')
```

### Actual

Having a problem trying to require a virtual module that is not in the `node_modules` directory.  The following error shows on terminal.

```bash
$ npx webpack --config webpack.config.js

Hash: 68ea1406c3585126b4b9
Version: webpack 4.39.3
Time: 85ms
Built at: 09/06/2019 12:23:47 PM
          Asset      Size  Chunks             Chunk Names
index.bundle.js  3.99 KiB   index  [emitted]  index
Entrypoint index = index.bundle.js
[./src/index.js] 52 bytes {index} [built]

ERROR in ./src/index.js
Module not found: Error: Can't resolve './assets/number-one.js' in '/server/node/webpack/custom'
 @ ./src/index.js
```

### Recreate

The following is the code I wrote.

```js
//# FILE: webpack.config.js
const path = require('path');
const VirtualModulesPlugin = require('webpack-virtual-modules');

module.exports = {
  mode: 'development',
  entry: {
    index: './src/index.js'
  },
  output: {
    filename: '[name].bundle.js',
    path: path.resolve(__dirname, 'public')
  },
  plugins: [
    new VirtualModulesPlugin({
      'assets/number-one.js': 'module.exports = 1'
    })
  ]
};
```

```js
//# File: ./src/index.js
require('./assets/number-one.js')
```

**Comment by vlasenko** [comment]
@cblanquera You create virtual file at the location `/server/node/webpack/custom/assets/number-one.js`. Your entry point is inside `custom/src` folder. Thats why your import should rather be:
```
//# File: ./src/index.js
require('../assets/number-one.js')
```
Notice two dots at the beginning: `../`

**Comment by cblanquera** [comment]
Thanks for the reply. You are correct. Thanks again!

**Comment by iongion** [comment]
I am also unable to know the require/import module id.

```
const virtualModules = new VirtualModulesPlugin({
  './src/project-core/TestBundle.ts': specBundle.join('\n'),
});
```
In `src/project-core/Tester.tsx` I have

`require('./TestBundle');`

But I get

`Module not found: Error: Can't resolve './TestBundle' in '/Workspace/tsapp/src/project-core'`

What am I doing wrong ?

**Comment by larixer** [comment]
@iongion This issue has been resolved, please open new issue with exact reproduction steps.
