### ISSUE TITLE
Module Not Found When Using index.js

### ISSUE THREAD

**Issue by cblanquera** [sysgears/webpack-virtual-modules#30]
Hello again, another small issue found.

### Expected

Trying to add a Virtual Module located (virtually) where the endpoint is `./assets/number-one/index.js`. Other JS files in the same directory should be able to access this file using `./assets/number-one` *(where the `index.js` is omitted)*. For example in the entry file, the `/asset/number-one/index.js` can be required like the following.

```js
require('./asset/number-one')
```

and another random file `/something/random.js` could require `/asset/number-one/index.js` like the following.

```js
require('../asset/number-one')
```

### Actual

Having a problem trying to resolve modules that is using `index.js` as the virtual endpoint.  The following error shows on terminal.

```bash
$ npx webpack --config webpack.config.js
Hash: 4b46b354a8279f7e6198
Version: webpack 4.39.3
Time: 81ms
Built at: 09/09/2019 3:33:54 PM
          Asset      Size  Chunks             Chunk Names
index.bundle.js  3.93 KiB   index  [emitted]  index
Entrypoint index = index.bundle.js
[./entry.js] 30 bytes {index} [built]

ERROR in ./entry.js
Module not found: Error: Can't resolve './assets/number-one' in '/server/node/virtual-modules-test'
 @ ./entry.js 1:0-30
```

### Recreate

The following is the code I wrote.

```js
//# FILE: webpack.config.js
const path = require('path');
const VirtualModulesPlugin = require('webpack-virtual-modules');

module.exports = {
  mode: 'development',
  entry: {
    index: './entry.js'
  },
  output: {
    filename: '[name].bundle.js',
    path: path.resolve(__dirname, 'public')
  },
  plugins: [
    new VirtualModulesPlugin({
      './entry.js': 'require(\'./assets/number-one\')',
      './assets/number-one/index.js': 'module.exports = 1'
    })
  ]
};
```

##### 1. Not using `index.js`

I could refactor the config to use `./assets/number-one.js` like the following snippet.

```js
...
plugins: [
    new VirtualModulesPlugin({
      './entry.js': 'require(\'./assets/number-one\')',
      './assets/number-one.js': 'module.exports = 1'
    })
  ]
...
```

but trying to convert an actual module (outside of the public directory) to a virtual module could be cumbersome. Consider the following series of files that would not work.

```js
...
plugins: [
    new VirtualModulesPlugin({
      './entry.js': 'require(\'./assets/number-one\')',
      './assets/number-one/index.js': 'require(\'./number-2\')'
      './assets/number-one/number2.js': 'module.exports = 2'
    })
  ]
...
```

##### 2. Not using VirtualModulesPlugin for this purpose.

In the normal webpack way, `index.js` is resolved *(but for my purpose I would need to do a symlink to path an arbitrary directory into the public path build)*. I could also consider using `alias` instead as well *(but lose the relative pathing)*.  Maybe some advice instead?

**Comment by cblanquera** [comment]
I was tinkering around extending the VirtualModulesPlugin to process an entire folder. The following plugin is how it looks like so far.

```js
//# FILE: VirtualDirectoryPlugin.js
const fs = require('fs');
const path = require('path');

const VirtualModulesPlugin = require('webpack-virtual-modules');

class VirtualDirectoryPlugin extends VirtualModulesPlugin {
  constructor(paths) {
    super({});
    //paths => { target: source }

    //lookup all files
    Object.keys(paths).forEach(target => {
      let virtual = null;
      for (const file of walk(paths[target])) {
        virtual = target + file.substr(paths[target].length);
        this._staticModules[virtual] = fs.readFileSync(file);
      }
    });
  }
}

module.exports = VirtualDirectoryPlugin;

function *walk(folder) {
  const files = fs.readdirSync(folder);

  for (const file of files) {
    const item = path.join(folder, file);
    if (fs.statSync(item).isDirectory()) {
      yield *walk(item);
    } else {
      yield item;
    }
  }
}
```

And this is how it would be called.

```js
//# FILE: webpack.config.js
...
plugins: [
    new VirtualModulesPlugin({
      './assets/number-one.js': 'module.exports = 1'
    }),
    new VirtualDirectoryPlugin({
      './module/product': path.resolve(__dirname, 'module/product')
    })
  ]
...
```

**Comment by vlasenko** [comment]
@cblanquera You can do:
```
...
plugins: [
    new VirtualModulesPlugin({
      './entry.js': 'require(\'./assets/number-one/index\')',
      './assets/number-one/index.js': 'require(\'./number-2\')'
      './assets/number-one/number2.js': 'module.exports = 2'
    })
  ]
...
```
E.g. be explicit about `./assets/number-one/index`

**Comment by cblanquera** [comment]
Thanks @vlasenko for the swift response. I'll consider the approach you mentioned.

**Comment by vlasenko** [comment]
@cblanquera In `webpack-virtual-modules@0.2.0` we create virtual dirs that lead to virtual file, so I think you should be able to use the code like this:
```
...
plugins: [
    new VirtualModulesPlugin({
      './entry.js': 'require(\'./assets/number-one\')',
      './assets/number-one/index.js': 'require(\'./number-2\')'
      './assets/number-one/number2.js': 'module.exports = 2'
    })
  ]
...
```
E.g. no need to be explicit about `number-one/index` anymore

**Comment by cblanquera** [comment]
That's great news. Thanks for the update @vlasenko  . Will check it out immediately :)
