### ISSUE TITLE
Files disappear and cannot be read by inputFileSystem

### ISSUE THREAD

**Issue by brandonkal** [sysgears/webpack-virtual-modules#31]
I am writing a CSS-in-JS CSS extraction loader. On the first webpack build, this appears to work fine. I use `Virtual.writeModule('file.js.extracted.css', contents)` and it is then picked up by the first CSS loader.

However, after the first compilation, `this.fs.readFileSync()` does not return contents.
I use that call to check if the file should be updated. But it just errors.
Then I call `Virtual.writeModule('file.js.extracted.css', contents)` which seems to work okay.
Stepping through, I see that the virtual files are there on the private property. But then the first CSS loader cannot read the file and emits an ENOENT: no such file or directory. This error comes from webpack's `graceful-fs`.

Is it possible to get this working in watch mode after the first 60 seconds since the start of the initial build?

**Comment by vlasenko** [comment]
@brandonkal This plugin is not mean to emulate `inputFileSystem`, it is meant to provide virtual modules that can be `require`-ed from source code compiled by webpack

**Comment by brandonkal** [comment]
@vlasenko Yes but even if that is the case, something is broken.
To clarify, this is how I have things wired up now.
1. My plugin calls VirtualModules.apply(compiler) in its apply method. The file then exports the instance.
2. My JS loader compiles the JS file and writes a require statement for the generated (virtual) CSS file.
3. The JS loader calls writeModule
4. Webpack evaluates JS, and on discovering the require statement, starts the CSS loader chain.

That works fine initially. But if the source file updates (so that my JS loader is again called) doing the above starts failing hard.

It seems like this should be supported because this module emits watchFileSystem events when writeModule is called.

It seems I am going to have to figure out how to wrap `inputFileSystem` so that it will read from the virtualModules which looks quite complex.

**Comment by vlasenko** [comment]
@brandonkal `webpack-virtual-modules` does indeed taps into `inputFileSystem` and `watchFileSystem`, but for the sole reason to fool webpack into thinking that the file is there on the fs and it changes when you call `writeModule`. The fs patching that is happening is not full, it just enough to cover this use case.

It would be great to have reproduction code to figure out whats happening.

**Comment by brandonkal** [comment]
If you are interested in digging into this @vlasenko, this is the [function that writes the updates](https://github.com/brandonkal/linaria/blob/3ba72594f370c9d62c8ee48651a44355d12014c5/src/loader.ts#L138). The issue occurs when the pitch function runs and updates dependent CSS files.

It is an extremely complex system though!
Making the loader async broke things where the CSS chain could not read the file even though a physical file was written.

Wrapping inputFileSystem to check the virtualModules first on read should work in my case. I can still use this plugin's logic to notify webpack of that a file has changed.
