### ISSUE TITLE
how to require the virtual module in plugin

### ISSUE THREAD

**Issue by vipcxj** [sysgears/webpack-virtual-modules#37]
In my plugin:
```ts
class MyPlugin {
    public apply(compiler: Compiler) {
        const virtualModules = new VirtualModulesPlugin({
            'path/to/module': JSON.stringify(someObj);
        })
        virtualModules.apply(compiler);
        compiler.hooks.compilation.tap(PLUGIN_NAME, (compilation) => {
            require('path/to/module') // failed.
            compilation.hooks.normalModuleLoader.tap(PLUGIN_NAME, () => {
                require('path/to/module') // still failed.
            })
        })
    }
}
```

**Comment by vlasenko** [comment]
This plugin produces "virtual modules" that can be required only by source code complied with webpack

**Comment by vipcxj** [comment]
How to get the require of webpack used in the source code ?

**Comment by vlasenko** [comment]
What do you mean? This plugin does not patch Node require. It patches webpack file systems so that webpack thought the virtual module is there when it compiles source code. So created virtual module is available on behalf of source code of your project, which is being compiled by webpack
