### ISSUE TITLE
Resolve dependency issue

### ISSUE THREAD

**Issue by yoonwaiyan** [sysgears/webpack-virtual-modules#44]
Hello, I installed React Storybook to my project but not sure why there's always dependency error from my yarn when I'm trying to run my webpack dev server:

```
error "@storybook/react#@storybook/core#webpack-virtual-modules#debug" is wrong version: expected "^3.0.0", got "2.6.9"
```

I don't see any dependency in the yarn.lock:
```
webpack-virtual-modules@^0.2.0:
  version "0.2.1"
  resolved "https://registry.yarnpkg.com/webpack-virtual-modules/-/webpack-virtual-modules-0.2.1.tgz#8ab73d4df0fd37ed27bb8d823bc60ea7266c8bf7"
  integrity sha512-0PWBlxyt4uGDofooIEanWhhyBOHdd+lr7QpYNDLC7/yc5lqJT8zlc04MTIBnKj+c2BlQNNuwE5er/Tg4wowHzA==
```

It worked when I preserve version 3.0.0  but and my yarn always strips away debug 3.0.0 each time  after running `yarn install`. 
```diff
-debug@^3.0.0, debug@^3.1.0, debug@^3.1.1, debug@^3.2.5:
+debug@^3.1.0, debug@^3.1.1, debug@^3.2.5:
   version "3.2.6"
   resolved "https://registry.yarnpkg.com/debug/-/debug-3.2.6.tgz#e83d17de16d8a7efb7717edbe5fb10135eee629b"
   integrity sha512-mel+jf7nrtEl5Pn1Qx46zARXKDpBbvzezse7p7LqINmdoIk8PYP5SySaxEmYv6TZ0JyEKA1hsCId6DIhgITtWQ==
```

Any idea how to resolve this?

**Comment by larixer** [comment]
@yoonwaiyan I'm afraid I need exact repro steps to help you with this issue. Otherwise you would better try luck on yarn `support-v1` channel on discord:
https://discordapp.com/invite/yarnpkg

Please reopen with repro steps.
