### ISSUE TITLE
[MODULE_NOT_FOUND] The npm's package "debug" is missing

### ISSUE THREAD

**Issue by enten** [sysgears/webpack-virtual-modules#5]
It's required at line 3:

```javascript
var debug = require('debug')('webpack-virtual-modules');
```

**Comment by vlasenko** [comment]
Pushed the fix into `0.1.6`

**Comment by vlasenko** [comment]
Hmm, seems the build is broken with the latest webpack. Going to look and fix the build tomorrow

**Comment by enten** [comment]
You added the "debug" npm's package as dev dependency (under the key "devDepenencies").

Should it be added as dependency instead (under the key "dependencies")?

**Comment by vlasenko** [comment]
@enten Yes, I agree. But the reason build fails now is due to changes in the latest Webpack.

**Comment by vlasenko** [comment]
@enten The build has been fixed via:
|https://github.com/sysgears/webpack-virtual-modules/commit/81ec55b7b92d42167888522268c60e2170392f85

**Comment by enten** [comment]
@vlasenko 
Thanks for your awesome work!
