### ISSUE TITLE
Impossible base case (TypeScript?)

### ISSUE THREAD

**Issue by eddow** [sysgears/webpack-virtual-modules#71]
**Describe the bug**

I don't know why but I seem unable to make the basic use-case work. I can find no way to have a virtual module declared with webpack using this plugin. I must miss a detail.

It is perhaps due to `ts-loader` or something, I really have no idea.

**To Reproduce**

[https://github.com/eddow/eddow-bug-expo](https://github.com/eddow/eddow-bug-expo)

**Screenshots**

```
ERROR in C:\dev\github\eddow-bug-expo\test\test1.ts
./test1.ts
[tsl] ERROR in C:\dev\github\eddow-bug-expo\test\test1.ts(1,22)
      TS2307: Cannot find module 'module-foo' or its corresponding type declarations.

ERROR in C:\dev\github\eddow-bug-expo\test\test2.ts
./test2.ts
[tsl] ERROR in C:\dev\github\eddow-bug-expo\test\test2.ts(1,22)
      TS2307: Cannot find module './module-foo' or its corresponding type declarations.
```

**Environment if relevant (please complete the following information):**

 - Node version v14.14.0
 - Webpack version 5.1.3

**Comment by larixer** [comment]
@eddow `ts-loader` cannot see the "virtual" file because it reads file system directly and does not rely on Webpack to get contents of your files. This is out of scope for the plugin.

**Comment by eddow** [comment]
Do you know any alternative that would allow me to use the plugin and typescript ?

**Comment by larixer** [comment]
@eddow No, I don't know
