### ISSUE TITLE
virtual-module-webpack-plugin

### ISSUE THREAD

**Issue by rmarscher** [sysgears/webpack-virtual-modules#73]
👋  I was randomly reading twitter and saw a tweet that gave a shout out to this project - https://twitter.com/Rich_Harris/status/1319022088989147138 - and then I noticed your readme linked to my project that experimentally did something similar. 😊 Thanks for that. I haven't tested Webpack 5, but it probably breaks my plugin. I'm thinking of updating my repository's readme to link to here and suggest that people use this project if they stumble on mine. I just wanted to give you a heads up. Let me know if you have any concerns. Otherwise, go ahead and close this issue and I'll push the update to my readme.
Cheers,
Rob

**Comment by larixer** [comment]
Hi @rmarscher ! Thanks for reaching out and thank you for creating your plugin it has showed that virtual modules are possible with webpack and inspired me to experiment with watch mode support, which was quite a slippery slope, but it is possible too even with newest webpack 5, which has numerous changes in watch mechanisms.

**Comment by rmarscher** [comment]
@larixer also see https://stackoverflow.com/a/36294904/304438 for the question that inspired me to figure out if it was possible.
