### ISSUE TITLE
[Bug] Creating virtual files on the fly causes infinite watched rebuilds

### ISSUE THREAD

**Issue by andyrooger** [sysgears/webpack-virtual-modules#74]
- [x] I'd be willing to submit the fix

**Describe the bug**

I don't necessarily know all the virtual files I want to create up front, so I've been creating them on a beforeResolve hook if they match a pattern. This worked fine up to and including 0.3.1. Since 0.3.2 this causes infinite rebuilds (which I guess makes sense given I'm creating files mid way through a build).

I'm not sure if this was ever a supported scenario so this may well be a feature request, but it was working until very recently

Is there a way to keep this working? Or alternatively a better approach?

**To Reproduce**

Add the following plugin to your webpack config and import `testfile.virtual.js` from a file in the build.
Start a watched build.

```ts
class ReproPlugin {
    apply(compiler) {
        const virtualModules = new VirtualModulesPlugin();
        virtualModules.apply(compiler);

        compiler.hooks.compilation.tap(this.constructor.name, (compilation, { normalModuleFactory }) => {
            normalModuleFactory.hooks.beforeResolve.tap(this.constructor.name, (result) => {
                if (/\.virtual\.js$/i.test(result.request)) {
                    virtualModules.writeModule(
                        path.resolve(result.context, result.request),
                        '// test content');
                }
                // uncomment if webpack < 5
                // return result;
            });
        });
    }
}
```

Prior to 0.3.2 this would build happily and wait for new changes. In 0.3.2 it builds repeatedly.

**Screenshots**

**Environment if relevant (please complete the following information):**

 - OS: Windows 10
 - Node version: 12.16.3
 - Webpack version: 5.3.2
- webpack-virtual-modules: 0.3.2

**Additional context**

The virtual files I'm creating don't exist in any form on disk so I wasn't able get a custom loader to work instead.

**Comment by larixer** [comment]
@andyrooger I'm not convinced it is a bug in `webpack-virtual-modules`, it seems like a bug in the code above. The argument, that this code worked before does not mean much, because before there were bugs in `webpack-virtual-modules` with watch mode support and now these bugs get fixed.

**Comment by andyrooger** [comment]
@larixer would this be a reasonable feature request instead then?

**Comment by larixer** [comment]
@andyrooger Maybe, but I don't see clear explanation what feature are you requesting? The feature request should be clearly explained to be understood for the future someone who will be willing to work on it.

**Comment by andyrooger** [comment]
@larixer I want to be able to create virtual files based on a pattern e.g. *.string.json rather than knowing exact file paths at the start of the compilation.

I guess it's better to open a new issue rather than reopening and rewording this one?

**Comment by larixer** [comment]
@andyrooger I think its not about naming of the files, its about when you call `writeModule`, you should not call `writeModule` with the same arguments more than once. In your example you are writing the same contents to the same virtual filename again and again and fall in a loop - this is expected and this is a problem in your code.

**Comment by andyrooger** [comment]
@larixer You're 100% right. I had assumed we didn't need to resolve the same path more than once in a compilation.

This works absolutely fine with latest webpack and webpack-virtual-modules

```js
class ReproPlugin {
    apply(compiler) {
        const virtualModules = new VirtualModulesPlugin();
        virtualModules.apply(compiler);

        const virtualized = new Set();

        compiler.hooks.compilation.tap(this.constructor.name, (compilation, { normalModuleFactory }) => {
            normalModuleFactory.hooks.beforeResolve.tap(this.constructor.name, (result) => {
                if (/\.virtual\.js$/i.test(result.request)) {
                    const fullPath = path.resolve(result.context, result.request);
                    if(!virtualized.has(fullPath)) {
                        virtualized.add(fullPath);
                        virtualModules.writeModule(fullPath, '// test content');
                    }
                }
                // uncomment if webpack < 5
                // return result;
            });
        });
    }
}
```

So no feature request needed and apologies for the spurious bug. Thank you, I appreciate the help.

**Comment by StephanGerbeth** [comment]
Hi,

Setup:
- nuxtjs 2.14
- webpack 4.4

i adapted the code part above to load remote images.

```
const VirtualModulesPlugin = require('webpack-virtual-modules')
const axios = require('axios')

module.exports = class VirtualPlugin {
  apply (compiler) {
    const virtualModules = new VirtualModulesPlugin()
    virtualModules.apply(compiler)

    const virtualized = new Set()

    compiler.hooks.compilation.tap(this.constructor.name, (compilation, { normalModuleFactory }) => {
      normalModuleFactory.hooks.beforeResolve.tapPromise(this.constructor.name, async (result) => {
        if (/^xyz\/assets\/virtual\.jpg/i.test(result.request)) {
          const filePath = 'assets/virtual.jpg'
          const file = `./example/${filePath}`

          if (!virtualized.has(`${file}`)) {
            result.request = `@/${filePath}`
            virtualized.add(`${file}`)
            const res = await axios.get('https://img.youtube.com/vi/5q0bcy17RT0/sddefault.jpg', { responseType: 'arraybuffer' })
            virtualModules.writeModule(`${file}`, res.data)
            return result
          }
        }
        return result
      })
    })
  }
}
```

it's working great, when I'm using it in the regular way
```
const test = require('xyz/assets/virtual.jpg')
```

but i can't combine it with image-loaders in this way
```
require('xyz/assets/virtual.jpg?lqip')
require('lqip-loaderxyz/assets/virtual.jpg')
```

I only got the following errors.
```
This dependency was not found:
* lqip-loader!xyz/assets/virtual.jpg in ...
```
```
This dependency was not found:
* xyz/assets/virtual.jpg?lqip
```

am I doing something wrong or how do I get it fixed?

Cheers
Stephan

**Comment by andyrooger** [comment]
@StephanGerbeth I suspect this could be that the virtual fs is having trouble using relative file paths - the path that is requested in the code being built may not have the same base as the virtual fs expects. Which is why I'm doing `path.resolve`.

I'm guessing though.

Is this use case better served with [resolve.alias](https://webpack.js.org/configuration/resolve/#resolvealias) or something like that?

**Comment by StephanGerbeth** [comment]
@andyrooger i reduced my sample code a little bit, so you can't see that i use absolute paths to register the content in virtual modules. sorry! 

if is use the same code, don't register the content in virtual modules but write the file directly on my hard disc. it is working properly. if i write it in virtual modules, the process can't find it anymore.

is it helpful to create a code sandbox to analyze the problem? should i create one?

**Comment by andyrooger** [comment]
@StephanGerbeth can do.

It's worth trying to populate the files early (in the virtual modules constructor or compilation hook) like in the readme examples and make sure the issue is not to do with how that virtual modules interacts with that plugin in general.

If not I'm happy to look through a sandbox, though I don't think I'm using the code above in conjunction with other loaders anywhere, so no guarantees I'll be able to make it work either :)
