### ISSUE TITLE
[Bug] Question: Trigger webpack rebuild

### ISSUE THREAD

**Issue by AustinGil** [sysgears/webpack-virtual-modules#86]
This is just a question:

Is there a way to trigger Webpack to trigger a recompile on file changes? I've got a JavaScript module that builds out CSS. That's what I'm loading as a virtual module. 

I've got mine building fine, but when I make changes to my file they are not showing up in my dev work. I have to restart webpack.
I've even tried using the webpack-watch-files-plugin to watch for changes and it looks like that is running fine, but my CSS changes do not get incorporated.

**Additional context**

The CSS module is being loaded the same way as in this thread: https://github.com/sysgears/webpack-virtual-modules/issues/70+

**Comment by non25** [comment]
@AustinGil maybe you will find this approach helpful: https://github.com/sveltejs/svelte-loader/pull/151

**Comment by Airkro** [comment]
https://github.com/sysgears/webpack-virtual-modules/issues/76

maybe relate, turn off cache might work

**Comment by ethangodt** [comment]
@AustinGil in the same boat. Did you find a solution for this?

**Comment by harlan-zw** [comment]
Specifically disabling the cache for the loader of the virtual module fixed my issue 

```
  this.cacheable(false)
```

**Comment by n8tz** [comment]
Hi there, 

I have a ( kind of complex ) way :) ..
To specifically force rebuilds of a module :
`
compiler.hooks.compilation.tap('layer-pack', ( compilation, params ) => {
				let toBeRebuilt = [];
				
				// force rebuild in wp5 
				compilation.buildQueue &&
				compilation.buildQueue.hooks &&
				compilation.buildQueue.hooks.beforeAdd
				           .tapAsync('layer-pack',
				                     ( module, cb ) => {
					                     if ( toBeRebuilt.includes(module.resource) ) {
						                     //console.info("Index was Updated ", module.resource, module._forceBuild)
						                     toBeRebuilt.splice(toBeRebuilt.indexOf(module.resource), 1);

						                     module._forceBuild = true; // <- this will force rebuilding the module
					                     }
					                     cb()
				                     }
				           );
				//  
				// put the path names of the virtual modules that were updated in toBeRebuilt


				
			})
`
And to watch things, if the "file/contextDependencies" doesn't work for you : 
`
compiler.hooks.afterDone
				        .tap('layer-pack', ( { compilation }, cb ) => {
					
					        // fix wp5 
					        compiler.options.watch
					        && process.nextTick(
						        tm => {
							        compiler.watchFileSystem.watcher.watch([/* files to watch */], [/* directories to watch */])
						        }
					        )
					
					        cache = {};
				        });
`
Using my plugin, layer-pack with big project (and too much deps) webpack do an endless loop when using fileDependencies & contextDependencies to specify fs watchs

You can see my code at https://github.com/layer-pack/layer-pack/blob/64db4bedd6d3245f69bffb6c3bcc0a9cefac8252/src/layerPackPlugin.js#L786

Hope it help :)

**Comment by JiangWeixian** [comment]
My project generate routes based file system, and write react routes object into virtual module.

I meet same issue, create new file didn't trigger rebuild, even write module on file `add` event.

```ts
compiler.hooks.compilation.tap(VMRoutesWebpackPluginName, async compiliation => {
  compiliation.contextDependencies.add(path.resolve(process.cwd(), 'src/pages'));
});
```

above code solve my problem, hope it help

**Comment by larixer** [comment]
Closing the issue as stale, please retest on latest `webpack-virtual-modules` and reopen with reproduction steps if the issue still exists.
